language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - AWS_DEFAULT_REGION=us-east-1

install:
  - pip install .
  - pip install flake8


script:
  - py.test test/
  - flake8 . --max-line-length 120 --ignore E402,E712,E731,E211 --select E,F
